<a href="https://colab.research.google.com/github/SidZRed/pytorch_dl/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning - SidZRed

# Setting up pytorch


In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


# *Tensors*

**Scalars**

In [8]:
scalar = torch.tensor(5)
print(scalar)
print(scalar.ndim)
print(scalar.item())


tensor(5)
0
5


**Vector**

In [11]:
vector = torch.tensor([4,5])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([4, 5])
1
torch.Size([2])


**Matrix**

In [14]:
matrix = torch.tensor([[1,2,3],
                      [3,4,3],
                       [4,5,6]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2, 3],
        [3, 4, 3],
        [4, 5, 6]])
2
torch.Size([3, 3])


**Tensor**

In [15]:
Tensor = torch.tensor([[[
    [1,2,3],[4,5,6],[7,8,9]
]]])
print(Tensor)
print(Tensor.ndim)
print(Tensor.shape)

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])
4
torch.Size([1, 1, 3, 3])
